### ISSUE TITLE
Lab 26

### ISSUE THREAD

**Issue by ewhd** [codefellows/seattle-cyber-401d3#1]
The IP, Username, and Password information for all the various VMs for today is only included in a Readme file in the download package. While this is an entirely appropriate place for it, it should not be the _only_ place for it.

A couple of students asked me what the passwords were, and while they eventually checked the Readme and figure it out, I had no way to help them unless I had downloaded the (44gb) ova package for today.

At the very least, this needs to be accessible to instructors in the curriculum repo, and including it in the student repo wouldn't be a bad idea either.

Contents of README.txt
```
This baseline threat detection lab includes the following virtual machines (VMs):
- pfsense-corpnet
  - This pfSense router/firewall VM provides network services, including DHCP, to the LAN.
  - IP: 10.0.0.1
  - Web portal: 10.0.0.1
  - Interfaces:
    - WAN: Dynamic
    - LAN: 10.0.0.0/24
    - SPAN1 is duplicating LAN traffic out to the IDS VM
  - Login:
    - U: admin
    - P: admin
- winserv2019-dc1
  - This Windows Server 2019 VM acts as the domain controller and DNS server for the LAN.
  - IP: 10.0.0.4
  - Login: 
    - U: CORP\Administrator P: labuser1!
    - U: CORP\notadmin P: labuser1!
- win10
  - This Windows 10 Pro endpoint VM is joined to the CORP domain and is forwarding system logs to the SIEM.
  - IP: 10.0.0.7
  - Login: 
    - U: CORP\Administrator P: labuser1!
    - U: CORP\notadmin P: labuser1!
- siem
  - This Ubuntu Linux Server 20.10 VM is hosting Splunk Enterprise (Trial) and ingesting logs in real time from win10.
  - IP: 10.0.0.5 
  - Web portal: 10.0.0.5:8000
  - Login:
    - U: splunkadmin
    - P: splunkadmin
- kali
  - This Kali Linux 2020.4 VM will serve as your attack box for simulating threat actor behavior.
  - IP: 10.0.0.8
  - Login:
    - U: kali
    - P: kali
- ids
  - This Ubuntu Linux Desktop 20.04 VM will act as your IDS (Snort).
  - IP: 10.0.0.6
  - Login: 
    - U: Ubuntu
    - P: ubuntu
```
